---
- name: Check if external scheduler configuration exists
  ansible.builtin.shell: grep -qE '^[[:space:]]*EXTERNAL_SCHEDULER' /etc/one/sched.conf
  register: scheduler_check
  changed_when: false
  failed_when: false

- name: Add external scheduler configuration
  ansible.builtin.blockinfile:
    path: /etc/one/sched.conf
    block: |
      EXTERNAL_SCHEDULER = [
          SERVER = "{{ external_scheduler }}",
          PROXY = "",
          TIMEOUT = 10
      ]
  when: scheduler_check.rc != 0
  register: config_update

- name: Restart opennebula-scheduler service
  ansible.builtin.systemd:
    name: opennebula-scheduler
    state: restarted
  when: config_update.changed

- name: Install opennebula-provision
  ansible.builtin.package:
    name: opennebula-provision
    state: present

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install pip dependencies for OpenNebula Edge Clusters provisioning
  ansible.builtin.pip:
    name: "{{ oneprovision_pip_dependencies }}"
    state: present

- name: Install Terraform
  ansible.builtin.unarchive:
    src: "https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip"
    dest: /usr/local/bin
    remote_src: true
    mode: '0755'
    creates: /usr/local/bin/terraform

- name: Update FireEdge Port
  ansible.builtin.lineinfile:
    path: /etc/one/fireedge-server.conf
    regexp: '^port:\s*\d+$'
    line: "port: {{ fireedge_port }}"
  when: fireedge_port is defined

- name: Restart opennebula-fireedge service
  ansible.builtin.systemd:
    name: opennebula-fireedge
    state: restarted
  when: fireedge_port is defined

- name: Update Sunstone Port
  ansible.builtin.lineinfile:
    path: /etc/one/sunstone-server.conf
    regexp: '^port:\s*\d+$'
    line: "port: {{ sunstone_port }}"
  when: sunstone_port is defined

- name: Update Sunstone FireEdge public endpoint
  ansible.builtin.lineinfile:
    path: /etc/one/sunstone-server.conf
    regexp: '^public_fireedge_endpoint::\s*\d+$'
    line: "public_fireedge_endpoint:: {{ public_fireedge_endpoint }}"

- name: Restart opennebula-sunstone service
  ansible.builtin.systemd:
    name: opennebula-sunstone
    state: restarted
