---
- name: Clone Cognit Frontend repo
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    force: true
    version: "{{ version | default('main') }}"

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install pip dependencies
  ansible.builtin.pip:
    requirements: "{{ repo_dest }}/requirements.txt"
    state: present

- name: Configure COGNIT Frontend
  ansible.builtin.template:
    src: "{{ conf_file }}.j2"
    dest: "/etc/{{ conf_file }}"
    mode: "0644"

- name: Get PID of process running on COGNIT Frontend port
  ansible.builtin.command: lsof -ti:{{ api_port }}
  register: pid
  changed_when: pid.rc != 0

- name: Kill the process if it exists
  ansible.builtin.command: kill -9 {{ pid.stdout }}
  when: pid.stdout != ""
  ignore_errors: true

- name: Start COGNIT Frontend
  ansible.builtin.shell: |
    "nohup python3 {{ repo_dest }}/src/main.py > /var/log/uvicorn.log 2>&1 &"
  changed_when: false

- name: Wait for uvicorn to start
  ansible.builtin.wait_for:
    port: "{{ api_port }}"
    timeout: 5
