---
- name: Check current default route
  ansible.builtin.command: ip route show default
  register: current_route
  changed_when: false

- name: Remove existing default route
  ansible.builtin.command: ip route del default via 10.0.1.1 dev eth0
  when: "'10.0.1.1' in current_route.stdout"

- name: Add new default route
  ansible.builtin.command: ip route add default via {{ default_gateway }}
  when: "default_gateway not in current_route.stdout"

- name: Check if persistent route configuration exists
  ansible.builtin.stat:
    path: /etc/netplan/99-default-route.yaml
  register: route_config

- name: Configure persistent default route
  ansible.builtin.template:
    src: 99-default-route.yaml.j2
    dest: /etc/netplan/99-default-route.yaml
    mode: '0644'
  register: netplan_config
  when: not route_config.stat.exists

- name: Apply netplan changes
  ansible.builtin.command: netplan apply
  when: netplan_config.changed
