---
- name: Refresh package manager cache
  ansible.builtin.package:
    update-cache: true

- name: Set up Edge Cluster Frontend API
  ansible.builtin.include_tasks: api.yml

- name: Set up SSL for Edge Cluster Frontend API
  ansible.builtin.include_tasks: ssl.yml
