---
# TODO: Check oned is ee otherwise Prometheus could not exist
- name: Clone opennebula-extensions GitHub repository
  ansible.builtin.git:
    repo: https://github.com/SovereignEdgeEU-COGNIT/opennebula-extensions.git
    dest: "{{ extensions_repo }}"
  run_once: true

- name: Prometheus - Patch 1
  ansible.builtin.copy:
    src: "{{ extensions_repo }}/prometheus/patch_datasources.rb"
    remote_src: true
    dest: /usr/share/one/patch_datasources.rb
    owner: root
    group: root
    mode: '0644'

- name: Prometheus - Patch 2
  ansible.builtin.copy:
    src: "{{ extensions_repo }}/prometheus/vm_collector.rb"
    remote_src: true
    dest: /usr/lib/one/opennebula_exporter/opennebula_vm_collector.rb
    owner: root
    group: root
    mode: '0644'

- name: Prometheus - VM Hook
  ansible.builtin.command: "onehook create {{ extensions_repo }}/prometheus/vm.hook"
  register: hook_result
  failed_when: hook_result.rc != 0
  changed_when: hook_result.rc == 0

- name: Geolocation - Logic
  ansible.builtin.copy:
    src: "{{ extensions_repo }}/geolocation/geo.rb"
    remote_src: true
    dest: /usr/share/one/geo.rb
    owner: root
    group: root
    mode: '0644'

- name: Geolocation - VM Hook
  ansible.builtin.command: "onehook create {{ extensions_repo }}/geolocation/geo.hook"
  register: hook_result
  failed_when: hook_result.rc != 0
  changed_when: hook_result.rc == 0

- name: Delete opennebula-extensions GitHub repository
  file:
    path: "{{ extensions_repo }}"
    state: absent
