---
- name: Clone opennebula-extensions GitHub repository
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    version: "{{ one_extensions_version | default('main') }}"
  run_once: true

- name: Prometheus - Patch 1
  ansible.builtin.copy:
    src: "{{ repo_dest }}/prometheus/patch_datasources.rb"
    remote_src: true
    dest: /usr/share/one/patch_datasources.rb
    owner: root
    group: root
    mode: '0644'

- name: Prometheus - Patch 2
  ansible.builtin.copy:
    src: "{{ repo_dest }}/prometheus/vm_collector.rb"
    remote_src: true
    dest: /usr/lib/one/opennebula_exporter/opennebula_vm_collector.rb
    owner: root
    group: root
    mode: '0644'

- name: Prometheus - VM Hook
  ansible.builtin.command: "onehook create {{ repo_dest }}/prometheus/vm.hook"
  register: hook_result
  failed_when: hook_result.rc != 0
  changed_when: hook_result.rc == 0

- name: Geolocation - Logic
  ansible.builtin.copy:
    src: "{{ repo_dest }}/geolocation/geo.rb"
    remote_src: true
    dest: /usr/share/one/geo.rb
    owner: root
    group: root
    mode: '0644'

- name: Geolocation - VM Hook
  ansible.builtin.command: "onehook create {{ repo_dest }}/geolocation/geo.hook"
  register: hook_result
  failed_when: hook_result.rc != 0
  changed_when: hook_result.rc == 0

- name: Check if biscuit auth driver directory exists
  ansible.builtin.stat:
    path: "{{ repo_dest }}/biscuit"
  register: biscuit_driver

- name: Configure biscuit auth driver
  when: biscuit_driver.stat.exists
  block:
    - name: Install biscuit auth driver
      ansible.builtin.copy:
        src: "{{ repo_dest }}/biscuit"
        remote_src: true
        dest: /var/lib/one/remotes/auth
        owner: oneadmin
        group: oneadmin
        mode: '0750'

    - name: Enable biscuit auth driver
      ansible.builtin.lineinfile:
        path: /etc/one/oned.conf
        regexp: '^AUTHN\s*='
        line: 'AUTHN = "ssh,x509,ldap,server_cipher,server_x509,biscuit"'
        state: present

    - name: Add AUTH_MAD_CONF block to oned.conf
      ansible.builtin.blockinfile:
        path: /etc/one/oned.conf
        block: |
          AUTH_MAD_CONF = [
              NAME = "biscuit",
              PASSWORD_CHANGE = "YES",
              DRIVER_MANAGED_GROUPS = "NO",
              DRIVER_MANAGED_GROUP_ADMIN = "NO",
              MAX_TOKEN_TIME = "-1"
          ]
        state: present

    - name: Restart OpenNebula service
      ansible.builtin.systemd:
        name: opennebula
        state: restarted

- name: Delete opennebula-extensions GitHub repository
  ansible.builtin.file:
    path: "{{ repo_dest }}"
    state: absent
