---
- name: Setup frontend
  ansible.builtin.import_playbook: opennebula.deploy.main
- name: Setup external scheduler
  hosts: "{{ frontend_group | d('frontend') }}"
  tasks:
    - name: Add external scheduler configuration
      ansible.builtin.blockinfile:
        path: /etc/one/sched.conf
        block: |
          EXTERNAL_SCHEDULER = [
              SERVER = "{{ external_scheduler }}",
              PROXY = "",
              TIMEOUT = 10
          ]

    - name: Restart opennebula-scheduler service
      ansible.builtin.systemd:
        name: opennebula-scheduler
        state: restarted
    - name: Update FireEdge Port
      ansible.builtin.lineinfile:
        path: /etc/one/fireedge-server.conf
        regexp: '^port:\s*\d+$'
        line: "port: {{ fireedge_port }}"
    - name: Restart opennebula-fireedge service
      ansible.builtin.systemd:
        name: opennebula-fireedge
        state: restarted
    - name: Update Sunstone Port
      ansible.builtin.lineinfile:
        path: /etc/one/sunstone-server.conf
        regexp: '^:port:\s*\d+$'
        line: ":port: {{ sunstone_port }}"
    - name: Restart opennebula-sunstone service
      ansible.builtin.systemd:
        name: opennebula-sunstone
        state: restarted
- name: Setup provision-engine
  hosts: "{{ engine_group | d('engine') }}"
  roles:
    - engine
- name: Setup opennebula-extensions
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - opennebula-extensions
- name: Setup ai-orchestrator
  hosts: "{{ ai_group | d('ai') }}"
  roles:
    - ai
