---
- ansible.builtin.import_playbook: opennebula.deploy.main
- name: Setup provision-engine
  hosts: "{{ engine_group | d('engine') }}"
  become: true
  vars:
    oned: http://ec2-18-210-17-57.compute-1.amazonaws.com:2633/RPC2
    oneflow: http://ec2-18-210-17-57.compute-1.amazonaws.com:2474
  roles:
    - engine
