---
- name: Setup frontend
  ansible.builtin.import_playbook: opennebula.deploy.main
- name: Setup provision-engine
  hosts: "{{ engine_group | d('engine') }}"
  roles:
    - engine
- name: Setup opennebula-extensions
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - opennebula-extensions
