---
- name: Setup ingress node
  hosts: "{{ ingress_group | d('ingress') }}"
  roles:
    - reverse_proxy
    - nat_gateway

- name: Setup frontend routing
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - route

- name: Setup frontend
  ansible.builtin.import_playbook: opennebula.deploy.main

- name: Setup COGNIT frontend
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - opennebula-extensions
    - cognit_frontend

- name: Setup provision-engine
  hosts: "{{ engine_group | d('engine') }}"
  roles:
    - route
    - engine

# TODO: Enable when instructions are provided
# - name: Setup ai-orchestrator
#   hosts: "{{ ai_group | d('ai') }}"
#   roles:
#     - route
#     - ai
