---
- name: Setup ingress node
  hosts: "{{ ingress_group | d('ingress') }}"
  roles:
    - reverse_proxy
    - nat_gateway

- name: Apply routing to all relevant hosts
  hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ cognit_frontend_group | d('cognit_frontend') }}"
    - "{{ ai_group | d('ai') }}"
  roles:
    - route

- name: Install OpenNebula
  ansible.builtin.import_playbook: opennebula.deploy.main

- name: Setup COGNIT Cloud-Edge Manager
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - opennebula-extensions
    - one_frontend

- name: Setup COGNIT Frontend
  hosts: "{{ cognit_frontend_group | d('cognit_frontend') }}"
  roles:
    - cognit_frontend

- name: Setup ai-orchestrator
  gather_facts: true
  hosts: "{{ ai_group | d('ai') }}"
  roles:
    - ai
