---
- name: Setup ingress node
  hosts: "{{ ingress_group | d('ingress') }}"
  roles:
    - reverse_proxy
    - nat_gateway

- name: Apply routing to all relevant hosts
  hosts:
    - "{{ frontend_group | d('frontend') }}"
    - "{{ engine_group | d('engine') }}"
    - "{{ ai_group | d('ai') }}"
  roles:
    - route

- name: Install OpenNebula
  ansible.builtin.import_playbook: opennebula.deploy.main

- name: Setup COGNIT Cloud-Edge Manager
  hosts: "{{ frontend_group | d('frontend') }}"
  roles:
    - biscuit
    - opennebula-extensions
    - cognit_frontend # TODO: Rename to cognit opennebula frontend

- name: Setup provision-engine
  hosts: "{{ engine_group | d('engine') }}"
  roles:
    - engine

- name: Setup ai-orchestrator
  hosts: "{{ ai_group | d('ai') }}"
  roles:
    - ai
