---
- name: Download Biscuit CLI
  ansible.builtin.get_url:
    url: "https://github.com/biscuit-auth/biscuit-cli/releases/download/{{ biscuit_version }}/biscuit-{{ biscuit_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "{{ biscuit_tmp }}.tar.gz"
  mode: '0755'

- name: Extract Biscuit CLI
  ansible.builtin.unarchive:
    src: "{{ biscuit_tmp }}.tar.gz"
    dest: /tmp
    remote_src: true

- name: Install Biscuit CLI
  ansible.builtin.copy:
    src: "{{ biscuit_tmp }}/biscuit"
    remote_src: true
    dest: "/usr/bin"
    mode: '0755'

- name: Clean up temporary files
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ biscuit_tmp }}.tar.gz"
    - "{{ biscuit_tmp }}"
