---
- name: Clone Provigion Engine repo
  ansible.builtin.git:
    repo:  "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    force: true

- name: Install Ruby
  become: true
  block:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - ruby
          - ruby-dev
          - build-essential
          - zlib1g-dev
        state: present
        update_cache: true

- name: Install engine
  ansible.builtin.command:
    cmd: "./install.sh"
    chdir: "{{ repo_dest }}"

- name: Set the engine to listen on every host
  lineinfile:
    path: /etc/provision-engine/engine.conf
    regexp: '^:host:'
    line: ':host: 0.0.0.0'

- name: Set the engine port
  lineinfile:
    path: /etc/provision-engine/engine.conf
    regexp: '^:port:'
    line: ":port: {{ engine_port }}"

- name: Point Engine to frontend
  ansible.builtin.command:
    cmd: "./prepare.rb {{ oned }} {{ oneflow }}"
    chdir: "{{ repo_dest }}/tests"

- name: Start engine
  ansible.builtin.command: provision-engine-server start
  ignore_errors: true

- name: Check if engine port is being used
  ansible.builtin.wait_for:
    port: "{{ port }}"
    timeout: 5
