---
- name: Clone Cognit Frontend repo
  ansible.builtin.git:
    repo: "{{ repo_url }}"
    dest: "{{ repo_dest }}"
    force: true
    version: "{{ version | default('main') }}"

- name: Install python3-pip
  ansible.builtin.package:
    name: python3-pip
    state: present

- name: Install pip dependencies
  ansible.builtin.pip:
    requirements: "{{ repo_dest }}/requirements.txt"
    state: present

- name: Configure Edge Cluster Frontend
  ansible.builtin.template:
    src: "{{ conf_file }}.j2"
    dest: "/etc/{{ conf_file }}"

- name: Start Edge Cluster Frontend
  ansible.builtin.shell: |
    "nohup python3 {{ repo_dest }}/src/main.py > /var/log/uvicorn.log 2>&1 &"

- name: Wait for uvicorn to start
  ansible.builtin.wait_for:
    port: "{{ api_port }}"
    timeout: 5
